import {
  Atom,
  Bell,
  Bike,
  Bolt,
  Book,
  Box,
  BrandGithub,
  Briefcase,
  Brush,
  BuildingCommunity,
  BuildingSchool,
  BuildingSkyscraper,
  BuildingStore,
  CalendarTime,
  Camera,
  Car,
  ChartBar,
  Checklist,
  Cloud,
  Code,
  Coffee,
  Coin,
  Cpu,
  Database,
  DeviceDesktop,
  DeviceGamepad,
  DeviceLaptop,
  DeviceMobile,
  Flag,
  Flame,
  Folder,
  GitBranch,
  Headset,
  Heart,
  Home,
  Key,
  LayoutKanban,
  Leaf,
  Lock,
  Mail,
  Map,
  Message,
  Microphone,
  Mountain,
  Music,
  News,
  Notebook,
  Package,
  Palette,
  Photo,
  Plane,
  Plant,
  Puzzle,
  ReportAnalytics,
  Robot,
  Rocket,
  Server,
  Settings,
  Shield,
  ShoppingCart,
  Sparkles,
  Speakerphone,
  Star,
  Target,
  Tools,
  Tree,
  Trophy,
  Users,
  Video,
  Wallet,
  World,
} from '@appica/icons-react';
import type { ComponentType } from 'react';

export const DEFAULT_PROJECT_ICON = 'Folder';

const projectIcons = {
  Folder,
  Rocket,
  LayoutKanban,
  Checklist,
  Code,
  BrandGithub,
  GitBranch,
  Database,
  Server,
  Cloud,
  Cpu,
  Robot,
  DeviceLaptop,
  DeviceDesktop,
  DeviceMobile,
  DeviceGamepad,
  World,
  BuildingCommunity,
  BuildingSkyscraper,
  BuildingStore,
  BuildingSchool,
  Home,
  Briefcase,
  ShoppingCart,
  ChartBar,
  ReportAnalytics,
  Target,
  Trophy,
  Flag,
  Puzzle,
  Tools,
  Settings,
  Shield,
  Lock,
  Key,
  Users,
  Mail,
  Message,
  Bell,
  CalendarTime,
  Book,
  Notebook,
  News,
  Palette,
  Brush,
  Photo,
  Camera,
  Video,
  Music,
  Microphone,
  Headset,
  Speakerphone,
  Map,
  Car,
  Plane,
  Bike,
  Atom,
  Bolt,
  Flame,
  Sparkles,
  Star,
  Heart,
  Leaf,
  Plant,
  Tree,
  Mountain,
  Coffee,
  Coin,
  Wallet,
  Box,
  Package,
} satisfies Record<string, ComponentType<{ 'aria-hidden'?: boolean | 'true' | 'false'; className?: string }>>;

export type ProjectIconName = keyof typeof projectIcons;

export const PROJECT_ICON_NAMES = Object.keys(projectIcons) as ProjectIconName[];

export function isProjectIconName(value: string | null | undefined): value is ProjectIconName {
  return Boolean(value && value in projectIcons);
}

export function ProjectIcon({
  name,
  className,
}: {
  name?: string | null;
  className?: string;
}) {
  const Icon = isProjectIconName(name) ? projectIcons[name] : projectIcons[DEFAULT_PROJECT_ICON];
  return <Icon aria-hidden="true" className={className} />;
}
